=== eawag-rdm/datacite-to-opendataswiss/mappings/datacite-to-dcat-ap-ch/schema_datacite-v4d6-to-dcat-ap-ch-v2-mandatory.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "metadataVersions": {
            "type": "object",
            "properties": {
                "DataCite": {
                    "type": "object",
                    "properties": {
                        "version": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "url",
                        "version"
                    ]
                },
                "DCAT-AP-CH": {
                    "type": "object",
                    "properties": {
                        "version": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "url",
                        "version"
                    ]
                }
            },
            "required": [
                "DCAT-AP-CH",
                "DataCite"
            ]
        },
        "identifier": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "titles": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "publisher": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "contributors": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "descriptions": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        }
    },
    "required": [
        "contributors",
        "descriptions",
        "identifier",
        "metadataVersions",
        "publisher",
        "titles"
    ]
}

=== eawag-rdm/datacite-to-opendataswiss/mappings/datacite-to-dcat-ap-ch/datacite-v4d6-to-dcat-ap-ch-v2-mandatory.json
{
  "metadataVersions": {
    "DataCite": {
      "version": "4.6",
      "url": "https://datacite-metadata-schema.readthedocs.io/en/4.6/"
    },
    "DCAT-AP-CH": {
      "version": "2.0",
      "url": "https://dcat-ap.ch/releases/2.0/dcat-ap-ch.html"
    }
  },
  "identifier": {
    "property": "identifier",
    "transform": "DataCitev4d6ToDCATv2"
  },
  "titles": {
    "property": "title",
    "transform": "DataCitev4d6ToDCATv2 extract first title"
  },
  "publisher": {
    "property": "publisher",
    "transform": "DataCitev4d6ToDCATv2"
  },
  "contributors": {
    "property": "contactPoint",
    "transform": "DataCitev4d6ToDCATv2"
  },
  "descriptions": {
    "property": "description",
    "transform": "DataCitev4d6ToDCATv2 extract first title"
  }
}
