=== eawag-rdm/datacite-to-opendataswiss/app/mappings/datacite-to-dcat-ap-ch/schema_datacite-v4d6-to-dcat-ap-ch-v2-all.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "metadataVersions": {
            "type": "object",
            "properties": {
                "DataCite": {
                    "type": "object",
                    "properties": {
                        "version": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "url",
                        "version"
                    ]
                },
                "DCAT-AP-CH": {
                    "type": "object",
                    "properties": {
                        "version": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "url",
                        "version"
                    ]
                }
            },
            "required": [
                "DCAT-AP-CH",
                "DataCite"
            ]
        },
        "identifier": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "titles": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "publisher": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "contributors": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "descriptions": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "subjects": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "dates": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "object",
                    "properties": {
                        "issued": {
                            "type": "object",
                            "properties": {
                                "@dateType": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "@dateType"
                            ]
                        },
                        "temporal": {
                            "type": "object",
                            "properties": {
                                "@dateType": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "@dateType"
                            ]
                        },
                        "modified": {
                            "type": "object",
                            "properties": {
                                "@dateType": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "@dateType"
                            ]
                        }
                    },
                    "required": [
                        "issued",
                        "modified",
                        "temporal"
                    ]
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "properties",
                "transform"
            ]
        },
        "language": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "field",
                "transform"
            ]
        },
        "alternateIdentifiers": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "object",
                    "properties": {
                        "distribution": {
                            "type": "object",
                            "properties": {
                                "@alternateIdentifierType": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "@alternateIdentifierType"
                            ]
                        },
                        "landingPage": {
                            "type": "object",
                            "properties": {
                                "@landingPage": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "@landingPage"
                            ]
                        }
                    },
                    "required": [
                        "distribution",
                        "landingPage"
                    ]
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "properties",
                "transform"
            ]
        },
        "relatedIdentifiers": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "object",
                    "properties": {
                        "conformsTo": {
                            "type": "object",
                            "properties": {
                                "@relatedIdentifierType": {
                                    "type": "string"
                                },
                                "@relationType": {
                                    "type": "string"
                                },
                                "@resourceTypeGeneral": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "@relatedIdentifierType",
                                "@relationType",
                                "@resourceTypeGeneral"
                            ]
                        },
                        "page": {
                            "type": "object",
                            "properties": {
                                "@relatedIdentifierType": {
                                    "type": "string"
                                },
                                "@relationType": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "@relatedIdentifierType",
                                "@relationType"
                            ]
                        },
                        "isReferencedBy": {
                            "type": "object",
                            "properties": {
                                "@relatedIdentifierType": {
                                    "type": "string"
                                },
                                "@relationType": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "@relatedIdentifierType",
                                "@relationType"
                            ]
                        }
                    },
                    "required": [
                        "conformsTo",
                        "isReferencedBy",
                        "page"
                    ]
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "properties",
                "transform"
            ]
        },
        "rightsList": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "string"
                },
                "transform": {
                    "type": "string"
                }
            },
            "required": [
                "property",
                "transform"
            ]
        },
        "geoLocations": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "string"
                }
            },
            "required": [
                "properties"
            ]
        }
    },
    "required": [
        "alternateIdentifiers",
        "contributors",
        "dates",
        "descriptions",
        "geoLocations",
        "identifier",
        "language",
        "metadataVersions",
        "publisher",
        "relatedIdentifiers",
        "rightsList",
        "subjects",
        "titles"
    ]
}

=== eawag-rdm/datacite-to-opendataswiss/mappings/datacite-to-dcat-ap-ch/datacite-v4d6-to-dcat-ap-ch-v2-all.json
{
  "metadataVersions": {
    "DataCite": {
      "version": "4.6",
      "url": "https://datacite-metadata-schema.readthedocs.io/en/4.6/"
    },
    "DCAT-AP-CH": {
      "version": "2.0",
      "url": "https://dcat-ap.ch/releases/2.0/dcat-ap-ch.html"
    }
  },
  "identifier": {
    "property": "identifier",
    "transform": "DataCitev4d6ToDCATv2"
  },
  "titles": {
    "property": "title",
    "transform": "DataCitev4d6ToDCATv2 extract first title"
  },
  "publisher": {
    "property": "publisher",
    "transform": "DataCitev4d6ToDCATv2"
  },
  "contributors": {
    "property": "contactPoint",
    "transform": "DataCitev4d6ToDCATv2"
  },
  "descriptions": {
    "property": "description",
    "transform": "DataCitev4d6ToDCATv2 extract first title"
  },
  "subjects": {
    "property": "keyword",
    "transform": "DataCitev4d6ToDCATv2"
  },
  "dates": {
    "properties": {
      "issued": {
        "@dateType": "Issued"
      },
      "temporal": {
        "@dateType": "Coverage"
      },
      "modified": {
        "@dateType": "Updated"
      }
    },
    "transform": "DataCitev4d6ToDCATv2"
  },
  "language": {
    "field": "language",
    "transform": "DataCitev4d6ToDCATv2"
  },
  "alternateIdentifiers": {
    "properties": {
      "distribution": {
        "@alternateIdentifierType": "URL"
      },
      "landingPage": {
        "@landingPage": "URL"
      }
    },
    "transform": "DataCitev4d6ToDCATv2"
  },
  "relatedIdentifiers": {
    "properties": {
      "conformsTo": {
        "@relatedIdentifierType": "URL",
        "@relationType": "IsDescribedBy",
        "@resourceTypeGeneral": "Model"
      },
      "page": {
        "@relatedIdentifierType": "URL",
        "@relationType": "IsDocumentedBy"
      },
      "isReferencedBy": {
        "@relatedIdentifierType": "URL",
        "@relationType": "IsDocumentedBy"
      }
    },
    "transform": "DataCitev4d6ToDCATv2"
  },
  "rightsList": {
    "property": "accessRights",
    "transform": "DataCitev4d6ToDCATv2"
  },
  "geoLocations": {
    "properties": "spatial"
  }
}
